# Generated by Django 5.2.15 on 2026-06-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrescue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='general_location',
            field=models.CharField(choices=[('north', 'North'), ('east', 'East'), ('south', 'South'), ('west', 'West'), ('central', 'Central')], default='west', max_length=20),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='contact_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
