# Generated by Django 5.2.15 on 2026-06-23 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodrescue', '0002_establishment_general_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='requested_quantity',
        ),
    ]
