# Generated by Django 5.2.15 on 2026-06-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrescue', '0003_remove_reservation_requested_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlisting',
            name='category',
            field=models.CharField(choices=[('bakery', 'Bakery'), ('packaged_food', 'Packaged Food'), ('dry_goods', 'Dry Goods'), ('fresh_produce', 'Fresh Produce'), ('chilled', 'Chilled'), ('frozen', 'Frozen'), ('beverages', 'Beverages'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
