# Generated by Django 6.0.7 on 2026-07-30 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrescue', '0004_foodlisting_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='event_thumbnails/')),
                ('name', models.CharField(max_length=200)),
                ('area', models.CharField(choices=[('north', 'North'), ('east', 'East'), ('south', 'South'), ('west', 'West'), ('central', 'Central')], max_length=20)),
                ('address', models.TextField()),
                ('postal_code', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_events', to='foodrescue.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='DistributionEventItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_items', to='foodrescue.distributionevent')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_event_items', to='foodrescue.reservation')),
            ],
            options={
                'unique_together': {('event', 'reservation')},
            },
        ),
    ]
