# Generated by Django 6.0.7 on 2026-07-31 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrescue', '0005_distributionevent_distributioneventitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlisting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food_listing_images/'),
        ),
    ]
