# Generated by Django 6.0.7 on 2026-08-08 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrescue', '0006_foodlisting_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='application_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='organisation',
            name='certification_file',
            field=models.FileField(blank=True, null=True, upload_to='organisation_certifications/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='organisation',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='organisation',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='organisation_profile_images/'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='region',
            field=models.CharField(blank=True, choices=[('north', 'North'), ('east', 'East'), ('south', 'South'), ('west', 'West'), ('central', 'Central')], max_length=20),
        ),
        migrations.AddField(
            model_name='organisation',
            name='team_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='team_type',
            field=models.CharField(blank=True, choices=[('certified_charity', 'Certified Charity Organisation'), ('volunteer_group', 'Volunteer Group')], max_length=30),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='contact_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
