# Generated by Django 6.0.7 on 2026-08-09 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodrescue', '0007_organisation_application_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='region',
            new_name='general_location',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='team_type',
            new_name='organisation_type',
        ),
    ]
