# Generated by Django 6.0.7 on 2026-08-11 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrescue', '0008_rename_region_organisation_general_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='business_type',
            field=models.CharField(blank=True, choices=[('supermarket', 'Supermarket'), ('bakery', 'Bakery'), ('wholesaler', 'Wholesaler'), ('manufacturer', 'Manufacturer'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='establishment',
            name='certification_file',
            field=models.FileField(blank=True, null=True, upload_to='establishment_certifications/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='establishment',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='establishment',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='establishment_profile_images/'),
        ),
    ]
