# Generated by Django 6.0.7 on 2026-08-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrescue', '0009_establishment_business_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='establishment_marked_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='organisation_marked_completed',
            field=models.BooleanField(default=False),
        ),
    ]
