# Generated by Django 6.0.7 on 2026-09-12 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodrescue', '0010_reservation_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlisting',
            name='co2_saved_kg',
        ),
    ]
